package gestionusuarios;

import java.util.Arrays;

public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNuevoUsuario = new javax.swing.JButton();
        btnListadoUsuarios = new javax.swing.JButton();
        lblListadoUsuarios = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Usuarios");

        btnNuevoUsuario.setText("Nuevo Usuario");
        btnNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoUsuarioActionPerformed(evt);
            }
        });

        btnListadoUsuarios.setText("Listado de Usuarios");
        btnListadoUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListadoUsuariosActionPerformed(evt);
            }
        });

        lblListadoUsuarios.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblListadoUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevoUsuario)
                    .addComponent(btnListadoUsuarios))
                .addContainerGap(321, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btnNuevoUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListadoUsuarios)
                .addGap(18, 18, 18)
                .addComponent(lblListadoUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoUsuarioActionPerformed
        // TODO add your handling code here:
        if (frmNuevoUsuario == null || !frmNuevoUsuario.isVisible()) {
            frmNuevoUsuario = new NuevoUsuario();
            frmNuevoUsuario.setVisible(true);
        }

    }//GEN-LAST:event_btnNuevoUsuarioActionPerformed

    private void btnListadoUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListadoUsuariosActionPerformed
        // TODO add your handling code here:
        // Al pulsar el botón simplemente muestra el listado de usuarios en la etiqueta
        lblListadoUsuarios.setText(GestionUsuarios.cUsuarios.toString());
        
        
        //lblListadoUsuarios.setText(Arrays.toString(GestionUsuarios.usuarios));
    }//GEN-LAST:event_btnListadoUsuariosActionPerformed
    NuevoUsuario frmNuevoUsuario;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListadoUsuarios;
    private javax.swing.JButton btnNuevoUsuario;
    private javax.swing.JLabel lblListadoUsuarios;
    // End of variables declaration//GEN-END:variables
}
